receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Слушать на всех интерфейсах
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Этот адрес будет скрейпить Prometheus
  debug: {}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    # Добавьте это, если решите включить трассы/логи позже
    traces:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]