spring.application.name=veholder
spring.datasource.url=jdbc:postgresql://localhost:5432/veholder
#spring.datasource.url=jdbc:postgresql://db:5432/veholder
spring.datasource.username=tester_adm
spring.datasource.password=tester
spring.datasource.driver-class-name=org.postgresql.Driver

server.tomcat.threads.max=50
server.tomcat.threads.min-spare=20
server.tomcat.max-connections=80
server.tomcat.accept-count=90
server.tomcat.connection-timeout=2000

server.ssl.enabled=false

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# ???????? debug ????? ??? ???????????
#debug=true

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# File storage
file.export.directory=./exports

jwt.secret=your-256-bit-secret-key-must-be-at-least-32-chars
# 24 hours in secs:
jwt.expiration=86400

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#logging.file.name = ../../../logs/my-logs.log
#logging.file.directory = /home/boss/app-logs
#logging.level.root=info
#logging.level.org.skillsmart.veholder=debug
#logging.level.org.hibernate=info
#logging.level.org.springframework.http=info
#logging.level.org.springframework.web=info
#logging.level.org.springframework.security=info
#logging.level.org.springframework.security=fatal

# ????????? access log
#server.tomcat.accesslog.enabled=true
#server.tomcat.accesslog.directory=/home/boss/app-logs
#server.tomcat.accesslog.file-prefix=access
#erver.tomcat.accesslog.file-date-format=.yyyy-MM-dd
#server.tomcat.accesslog.pattern=combined
#server.tomcat.accesslog.suffix=.log
