name: Run Deploy Script

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deploy script
        run: |
          cd ~/ci_cd
          chmod +x deploy_tst.sh
          ./deploy_tst.sh
